apps/extras/job/urls.py
from django.urls import path
from .views import JobCreateView,JobUpdateView, JobDeleteView

app_name = "jobs"
urlpatterns = [
    path('create/', JobCreateView.as_view(), name="create-job"),
    path('update/<int:pk>', JobUpdateView.as_view(), name="update-job"),
    path('delete/<int:pk>', JobDeleteView.as_view(), name="delete-job"),
]

apps/extras/vacancy/urls.py
from django.urls import path
from .views import ApplyJobView, select_for_exam,cancel_for_exam, view_cv

app_name = "vacancy"
urlpatterns = [
    path('apply/<int:pk>', ApplyJobView.as_view(), name="apply"),
    path('interview/<int:application_id>', select_for_exam, name="exam"),
    path('cancle-exam/<int:application_id>', cancel_for_exam, name="cancel-exam"),
    path('view-cv/<int:application_id>', view_cv, name="view-cv")
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from config.views import assetlinks


urlpatterns = [
    path('.well-known/assetlinks.json', assetlinks, name='assetlinks'),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path("accounts/", include("apps.account.urls"), name='accounts'),
    path('', include('apps.core.urls')),
    path('', include('apps.extras.legal.urls'), name="legal"),
    path('jobs/', include('apps.extras.job.urls'), name="jobs"),
    path('vacancy/', include('apps.extras.vacancy.urls'), name="vacancy"),



    
    path('m1planning/', include('apps.modules.m1planning.urls'), name="planning"),
  
    path('recruit/', include('apps.modules.m2recruit.urls'), name="recruit"),
    path('onboarding/', include('apps.modules.m3onboarding.urls'), name="onboarding"),
    path('kinerja/', include('apps.modules.kinerja4.urls'), name="kinerja"),
    path('learning/', include('apps.modules.learning5.urls'), name="learning"),
    path('compensation/', include('apps.modules.compensation6.urls'),
         name="compensation"),
    path('compliance/', include('apps.modules.compliance7.urls'), name="compliance"),
    path('industrial/', include('apps.modules.ir8.urls'), name="industrial"),
    path('continues_improvement/', include('apps.modules.m9improvement.urls'),
         name="continues_improvement"),
    path('area/', include('apps.modules.area.urls'), name="area"),
    path('inbox/', include('apps.modules.inbox.urls'), name="inbox"),


    path('psychometric/', include('apps.extras.psychometric.urls'),
         name="psychometric"),
    path('blog/', include('apps.extras.blog.urls')),  # Tambahkan ini
    path('', include('apps.extras.syarat_ketentuan.urls'), name="syarat_ketentuan"),

    path('api/tips/', include('api.tips.urls')),
    path('api/mitra/', include('api.mitra_borongan.urls')),
    path('api/consultation/', include('api.consultation.urls')),
    path('api/sertifikasi/', include('api.sertifikasi.urls')),
    path('api/pasar/', include('api.pasar.urls')),
    path('api/petunjuk/', include('api.petunjuk.urls')),
    path('app/waypoint', include('api.waypoint.urls')),
    

    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    *urlpatterns,
] + debug_toolbar_urls()

apps/extras/job/models.py
from django.db import models
from django.conf import settings


class Jobs(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False)
    team_lead = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_DEFAULT, default=1, blank=False)
    required_position = models.CharField(max_length=100, blank=False, null=False)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.required_position+". "+self.title


class Application(models.Model):
    job = models.ForeignKey(Jobs, on_delete=models.SET_DEFAULT, null=True, blank=False, default=1)
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_DEFAULT, null=False, blank=False, related_name="applicant",
                                  default=1)
    cv = models.FileField(upload_to="media/cv", null=False, blank=False)
    selected_for_exam = models.BooleanField(default=False)
    canceled_for_exam = models.BooleanField(default=False)
    exam_attended = models.BooleanField(default=False)

    obtained_marks = models.CharField(null=True, blank=True, default="0/0",max_length=10)

    def __str__(self):
        return self.job.required_position+". "+self.job.title + " by " + self.applicant.username

apps/extras/job/forms.py
from django.forms import ModelForm
from .models import Jobs


class JobForm(ModelForm):
    class Meta:
        model = Jobs
        exclude = ['', ]

apps/extras/job/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, FormView, ListView, UpdateView
from .models import Jobs
from .forms import JobForm


# Create your views here.
class JobCreateView(FormView):
    success_url = reverse_lazy('dashboard:index')
    template_name = 'Job/add-job.html'
    form_class = JobForm

    def form_valid(self, form):
        current_form = form.save(commit=False)
        team_lead = form.cleaned_data['team_lead']
        print(team_lead.id)
        if team_lead.user_position != 'TL':
            form.add_error("team_lead", "The team lead must be registered as a Team lead")
            return super().form_invalid(form)

        form.save(commit=True)

        return super().form_valid(form)


class JobUpdateView(UpdateView):
    template_name = "Job/edit-job.html"
    success_url = reverse_lazy('dashboard:index')
    form_class = JobForm
    queryset = Jobs.objects.all()


class JobDeleteView(DeleteView):
    model = Jobs
    success_url = reverse_lazy('dashboard:index')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

apps/extras/job/templates/Job/add-job.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% block content %}
  <div>
    <h2>Add Job</h2>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
          {{ message }}
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
    <div class="row">
      <form method="post" class="col col-lg-8 col-xl-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="mb-3 row">
            {{ field|add_label_class:"col-form-label col-sm-4" }}
            <div class="col-sm-8">
              {% if field.field.widget.input_type == 'select' %}
                {{ field|add_class:"form-select" }}
              {% else %}
                {{ field|add_class:"form-control" }}
              {% endif %}
              {% for error in field.errors %}<div class="text-danger fs-6">{{ error }}</div>{% endfor %}
            </div>
          </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Add Job</button>
      </form>
    </div>
  </div>
{% endblock content %}

apps/extras/job/templates/Job/edit-job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Job</title>
</head>
<body>
    <h2>Edit Jobs</h2>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Edit Job</button>
    </form>
</body>
</html>

apps/extras/job/templates/Job/list-job.html
<div class="job list">


    {% for job in jobs %}
        <div class="card" style="width: 100%; margin: 10px; padding: 10px">
          <div class="card-body">
            <h5 class="card-title">{{ job.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ job.required_position }}</h6>
            <p class="card-text">{{ job.description }}</p>
            {% if user.user_position == 'HR' %}
                <a href="{% url 'jobs:update-job' pk=job.pk %}" class="card-link"> Edit</a>
                <a href="{% url 'jobs:delete-job' pk=job.pk %}" class="card-link"> Delete</a>
            {% elif user.user_position == 'I' %}
                <a href="{% url 'vacancy:apply' pk=job.pk %}" class="card-link">Apply For Vacancy</a>
            {% elif user.user_position == 'TL' %}
                <a href="{% url 'questions:list' job_id=job.pk %}" class="card-link">Questions for exam</a>
            {% else %}
                     <!-- <a href="{% url 'user:login' %}" class="card-link">Login To Apply</a> -->
            {% endif %}
          </div>
        </div>

    {% endfor %}
</div>